### ISSUE TITLE
Follow up with Spike and Sameer about data structure

### ISSUE THREAD

**Issue by fureigh** [codeforamerica/eligible-for-what#16]
Corresponding to the stretch goal. Though it may not be possible to incorporate their still-in-progress data structure before the end of this engagement, if it is possible, I'd like to do it.

**Comment by fureigh** [comment]
...and I've somehow lost admin privileges for this repo again. Pinging @daguar.

**Comment by daguar** [comment]
Sorry about that! Was doing GitHub team cleanup a bit back and must have broken it. (GH's team model is... bad.) Should be fixed now!

**Comment by fureigh** [comment]
Appears to be fixed! Thanks, @daguar!

**Comment by fureigh** [comment]
(This issue is a subissue of #13.)

**Comment by fureigh** [comment]
Confirmed shared analysis. Eligibility criteria and service categories, which are central to this project, are collapsed in HSDS and Ohana. More detailed writeup to come.
